spring:
  profiles:
    default: local

  datasource:
    url: jdbc:h2:./circuit
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
